version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: ${MYSQL_CONTAINER_NAME}
    # volumes:
    #   - ./db:/docker-entrypoint-initdb.d
    #   - ./dev:/wp-dev
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - ${NETWORK_NAME}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PHPMYADMIN_CONTAINER_NAME}
    depends_on:
      - mysql
    ports:
      - "${PHPMYADMIN_PORT}:80"
    restart: always
    environment:
      - PMA_HOST=${PMA_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - ${NETWORK_NAME}

  wordpress:
    image: wordpress
    container_name: ${WORDPRESS_CONTAINER_NAME}
    depends_on:
      - mysql
    volumes:
      - ./src:/var/www/html
      - ./dev:/wp-dev 
    links:
      - mysql:mysql
    ports:
      - "${WORDPRESS_PORT}:80"
    restart: always
    environment:
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
    networks:
      - ${NETWORK_NAME}

networks:
  ${NETWORK_NAME}:
